### ISSUE TITLE
Develop the curriculum and content - Who covers what?

### ISSUE THREAD

**Issue by kipkurui** [mbbu/Introduction_to_Bioinformatics#1]
Thank you so much for agreeing to assist with this training. 

Kindly make suggestions as to which courses you would be willing to cover. We also need to create a program for the day, complete with time allocations and link to training materials.

**Comment by kibet-gilbert** [comment]
## Looking at Introduction Data Backup and Version control.
With regard a to Git and GitHub, we may need to answer the following questions:
1. What is GitHub? _Introduction, Creating an account and repos_
2. What are the basic components of GitHub repo: 
-The interface options; Code, issues, Pull requests, Projects, wikis, Insights, watch*, start*, Fork, branch.
-Organization of a bioinformatics project repo; _introduction_
-README.md; [GitHub Flavored Markdown (GFM) _introduction_](https://github.github.com/gfm/#container-blocks)
3. What is Git and its use in version control? 
-Command line basics; `git clone`, and `git init`, `git add`, `git commit [-m]`, `git push`
-Github/Gitlab/Bitbucket
4. Finally why `git` and GitHub
5. A good sample GitHub profile and repo of a bioinformatics project and the icipes MBBU GitHub repo

**Comment by kipkurui** [comment]
Thanks, @kibet-gilbert that would be great. Kindly have a look at the materials we have previously used for training in these topics. We may also need a quick introduction to Commandline.
